# mkdocs.yml
site_name: Calculation Docs Main

theme:
  name: "material"

plugins:
  - mkdocstrings

nav:
  - Calculation Docs: index.md
  - tutorials.md
  - How-To Guides: how-to-guides.md
  - reference.md
  - explanation.md



  # https://realpython.com/python-project-documentation-with-mkdocs/#demo